[theme]
primaryColor = "#8B4513"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5DC"
textColor = "#1E1E1E"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
